version: '3.9'

services:
  postgres_exporter:
    # https://habr.com/ru/articles/578744/
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      DATA_SOURCE_URI: "postgres:5432/'${POSTGRES_DB}'?sslmode=disable"
      DATA_SOURCE_USER: $POSTGRES_USER
      DATA_SOURCE_PASS: $POSTGRES_PASSWORD
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - .etc/postgres_exporter/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M